{"time":"2025-08-18T18:04:48.4448186+02:00","level":"INFO","msg":"stream: starting","core version":"0.21.1"}
{"time":"2025-08-18T18:04:48.9049157+02:00","level":"INFO","msg":"stream: created new stream","id":"syay9qa4"}
{"time":"2025-08-18T18:04:48.9049157+02:00","level":"INFO","msg":"stream: started","id":"syay9qa4"}
{"time":"2025-08-18T18:04:48.9049157+02:00","level":"INFO","msg":"writer: started","stream_id":"syay9qa4"}
{"time":"2025-08-18T18:04:48.9049157+02:00","level":"INFO","msg":"handler: started","stream_id":"syay9qa4"}
{"time":"2025-08-18T18:04:48.9049157+02:00","level":"INFO","msg":"sender: started","stream_id":"syay9qa4"}
{"time":"2025-08-18T18:05:23.7427928+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.125.56.220:53592->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-18T18:05:26.1112668+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/salvatore-nocita25-politecnico-di-torino/truncated_newton/syay9qa4/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-18T18:05:46.8147204+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-18T18:05:49.6258618+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/salvatore-nocita25-politecnico-di-torino/truncated_newton/syay9qa4/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-18T18:06:12.5271184+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-18T18:06:15.5674497+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/salvatore-nocita25-politecnico-di-torino/truncated_newton/syay9qa4/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-18T18:06:16.2099675+02:00","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading data","runtime_seconds":71.1507033,"error_status":"retrying: Post \"https://api.wandb.ai/files/salvatore-nocita25-politecnico-di-torino/truncated_newton/syay9qa4/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-08-18T18:06:22.0887482+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-08-18T18:06:24.0967419+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/salvatore-nocita25-politecnico-di-torino/truncated_newton/syay9qa4/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-08-18T18:06:41.2542137+02:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-08-18T18:06:46.2154053+02:00","level":"INFO","msg":"stream: closing","id":"syay9qa4"}
{"time":"2025-08-18T18:06:46.2154053+02:00","level":"INFO","msg":"handler: closed","stream_id":"syay9qa4"}
{"time":"2025-08-18T18:06:46.2154053+02:00","level":"INFO","msg":"sender: closed","stream_id":"syay9qa4"}
{"time":"2025-08-18T18:06:46.2154053+02:00","level":"INFO","msg":"stream: closed","id":"syay9qa4"}
